pipeline {
  agent any
  
  stages {
    stage('Build') {
      steps {

        sh 'mvn clean install'  
      }
    }
    
    stage('Deploy') {
      steps {
        // Deploy the code to the EC2 instance using SSH
        
        withCredentials([sshUserPrivateKey(credentialsId: 'ssh_id', keyFileVariable: 'ssh_key')]) {
          sh '''
            ssh -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ubuntu@192.168.11.34 "/home/ubuntu/myapp/deployment; git pull origin master"
            ssh -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ubuntu@192.168.11.34 "sudo systemctl restart nginx"
          '''
        }
      }
    }
  }
}